version: '3.3'
services:
    prometheus:
        image: prom/prometheus:v2.22.0
        ports:
            - '9090:9090'
        command:
        - --config.file=/etc/prometheus/prometheus.yaml
        volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
        depends_on:
        - csvserver
    csvserver:
        ports:
            - '9393:9300'
        container_name: csvserver
        env_file:
            - csvserver.env
        volumes:
            - './inputFile:/csvserver/inputdata'
        image: 'infracloudio/csvserver:latest'
